INSERT INTO USER(ID, USERNAME, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, ACCOUNT_EXPIRED, LOCKED, CREDENTIALS_EXPIRED,
                 ENABLED)
VALUES (1, 'Hasatori', 'hradil.o@email.cz', 'Oldřich', 'Hradil',
        '$2a$10$JSqrJ4lIOCTyf1/GXSYiVOoyyiR.fVemo9EMU1qDkIzxZhyI4XrIa', FALSE, FALSE, FALSE, TRUE);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (1, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (2, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (3, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (4, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (5, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (6, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (7, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (8, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (9, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (10, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (11, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (12, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (13, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (14, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (15, 1, '2019-10-05', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (16, 1, '2019-10-04', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (17, 1, '2019-10-04', 0, 0, true, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (18, 1, '2019-10-04', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (19, 1, '2019-10-04', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (20, 1, '2019-10-04', 0, 0, true, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (21, 1, '2019-10-04', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (22, 1, '2019-10-04', 0, 0, false, 0);
INSERT INTO POMODORO(ID, USER, DATE, WORK_TIME_REMAINING, BREAK_TIME_REMAINING, INTERRUPTED, NUMBER_OF_INTERRUPTIONS)
VALUES (23, 1, '2019-10-04', 0, 0, false, 0);
