INSERT INTO USER(ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD) VALUES(1,'hradil.o@email.cz','Oldřich','Hradil','$2a$10$JSqrJ4lIOCTyf1/GXSYiVOoyyiR.fVemo9EMU1qDkIzxZhyI4XrIa');
INSERT INTO POMODORO(ID,USER,DATE,WORK_TIME_REMAINING,BREAK_TIME_REMAINING,INTERRUPTED,NUMBER_OF_INTERRUPTIONS) VALUES(1,1,'2019-09-27',1500,300,false,0);
